### ISSUE TITLE
Group delay display clips

### ISSUE THREAD

**Issue by dsvf** [chipmuenk/pyFDA#142]
MWE: Lowpass, IIR, Butterworth, Order: Minimum, f_PB: 0.1, f_SB: 0.15, A_PB: 1dB, A_SB: 85dB
The result is a 24th-order filter. Looking at the group delay plot, there should be a peak of ~60 at f = 0.1. Instead, the graph is clipped as follows:
![grafik](https://user-images.githubusercontent.com/12519860/52563201-02e64080-2e01-11e9-913d-18bd26900d96.png)

**Comment by chipmuenk** [comment]
Thanx for  reporting, this failure is due to numerical inaccuracies. It is a corner case that fails with my grpdelay function (taken from the then scipy.signal bleeding edge years ago). It doesn't with the current `scipy.signal.group_delay`, so I replaced my version by importing the current scipy one.
Still, the design is on the verge of stability and I wouldn't use it for  any serious application; the order is simply too high.
I've committed the change to the 'develop' branch but as I'm in the middle of a large update to the fixpoint functionality it might still take a few weeks till the fix appears in the next master release.
