### ISSUE TITLE
SyntaxError: invalid syntax: reset = Reset(1, active=0, async=True)

### ISSUE THREAD

**Issue by yurivict** [chipmuenk/pyfda#200]
python-37 prints this error:
```
/usr/local/bin/python3.7 /tmp/tmpdhipfzyy.py
  File "/usr/local/lib/python3.7/site-packages/pyfda/fixpoint_widgets/iir_df1.py", line 234
    reset = Reset(1, active=0, async=True)
                                   ^
SyntaxError: invalid syntax

removing /tmp/tmpdhipfzyy.py
```

FreeBSD 12.2

**Comment by chipmuenk** [comment]
This file shouldn't be there, sorry. Please delete it if you can, it is a remainder of previous fixpoint implementations. But I don't quite understand why you're getting this error, the file shouldn't be used or imported anywhere. Are you running pyfda from the pyInstaller executable for Linux?

**Comment by yurivict** [comment]
This code is called autiomatically from ```setup.py install```.

**Comment by chipmuenk** [comment]
I guess most people use `pip install ... `, that's why the error hasn't been noticed earlier. Thanks for reporting, I'll make a new release in the next few days that fixes the bug. I've pushed the change to the master branch already, if you install directly from the latest git *master* branch everything should be fine.
